export const DATABASE_MANAGER_PROVIDER = 'DATABASE_CONNECTION';
export const DATABASE_TENANCY_PROVIDER = 'TENANCY_CONNECTION';
export const MONGO_MANAGER_PROVIDER = 'MONGO_CONNECTION';

export const NO_FOUND_CLIENT = 'NOT FOUND DATA OF CLIENT';

export const NAME_HEADER_CLIENT = 'x-mangus-client';
